# metrics.properties — expose les métriques Spark à Prometheus
# Spark les publie sur /metrics sur le port 8080

*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
*.sink.prometheusServlet.path=/metrics
master.sink.prometheusServlet.path=/metrics
applications.sink.prometheusServlet.path=/metrics