# Configuration de l'infrastructure Kafka
type: "kafka"
broker: "localhost:9092"
topic: "bank-transactions"

producer:
  api_version: [3, 7, 0]
  interval_sec: 1.0          # Fréquence d'envoi du simulateur intelligent
  # Configuration optionnelle pour la sérialisation
  value_serializer: "json"

consumer:
  starting_offsets: "latest"
  fail_on_data_loss: "false" # Empêche Spark de crasher si Kafka supprime de vieux messages