# =========================================================
# kafka/config/consumer.properties
# Configuration pour les tests locaux
# =========================================================

# L'adresse du broker à écouter
bootstrap.servers=localhost:9092

# Le nom du groupe de test
group.id=test-consumer-group

# Si le consumer se connecte en retard, doit-il lire depuis le début (earliest) 
# ou lire uniquement les nouveaux messages (latest) ?
auto.offset.reset=earliest