# =========================================================
# kafka/config/server.properties
# Configuration du Broker Kafka (Projet Fraude Bancaire)
# =========================================================

# 1. Identifiant unique du serveur
broker.id=0

# 2. L'adresse et le port sur lesquels Spark et le Producteur vont se brancher
listeners=PLAINTEXT://localhost:9092

# 3. Le dossier où Kafka va stocker temporairement les transactions sur le disque
log.dirs=C:/kafka/kafka-logs

# 4. Optimisation des Topics
# Nombre de partitions par défaut
num.partitions=1
# Autoriser la création automatique du topic si quelqu'un l'oublie
auto.create.topics.enable=true

# 5. Rétention de la donnée
log.retention.hours=168

# 6. Connexion à Zookeepere Kafka)
zookeeper.connect=localhost:2181
zookeeper.connection.timeout.ms=18000